OAuthToken: ""
AppLevelToken: ""
SigningSecret: ""
DatabaseHost: ""
DatabasePort: ""
DatabaseUsername: ""
DatabasePassword: ""
Database: ""
HistoricRangeYears: "1"
ScrapeCronExpression: "0 0 9,17 ? * *"